/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package menghitungnilaimahasiswa;
import java.io.BufferedReader; 
import java.io.BufferedWriter; 
import java.io.File; 
import java.io.FileWriter; 
import java.util.ArrayList; 
import javax.swing.JOptionPane; 
import javax.swing.table.DefaultTableModel; 


/**
 *
 * @author Marsy
 */
public class NilaiMahasiswa extends javax.swing.JFrame {
    public DefaultTableModel modelMahasiswa;
    public DataMahasiswa dataMahasiswa;
    /**
     * Creates new form NilaiMahasiswa
     */
        public NilaiMahasiswa() {
        initComponents();
        dataMahasiswa = new DataMahasiswa();
        TabelMahasiswa(); 
    }
    public final void TabelMahasiswa() {
        String[] columnNames = {"NIM", "Nama", "Alamat", "MataKuliah", "Nilai Akhir"};
        Object[][] objekMahasiswa = new Object[dataMahasiswa.getAllMahasiswa().size()][5];
        //prosese pendeklarasian
        int i = 0;
        for (Mahasiswa mhs : dataMahasiswa.getAllMahasiswa()) {
        Object arrayMahasiswa[] = {
            mhs.getNIM(),
            mhs.getNama(),
            mhs.getAlamat(),
            mhs.getMataKuliah(),  
            mhs.getNilaiAkhir()      
        };
        
        objekMahasiswa[i] = arrayMahasiswa;
        i++;
        }
                modelMahasiswa = new DefaultTableModel(objekMahasiswa, columnNames);
                TabelMahasiswa.setModel(modelMahasiswa);
    }
    public void ClearTextField(){  
    NIM.setText(""); 
    Nama.setText(""); 
    Alamat.setText(""); 
    MataKuliah.setText("");
    Nilai1.setText("");
    Nilai2.setText("");
    Nilai3.setText("");
    Nilai4.setText("");
    Nilai5.setText("");
    NilaiAkhir.setText("");
    } 


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        NIM = new javax.swing.JTextField();
        Nama = new javax.swing.JTextField();
        Alamat = new javax.swing.JTextField();
        MataKuliah = new javax.swing.JTextField();
        Nilai2 = new javax.swing.JTextField();
        Nilai3 = new javax.swing.JTextField();
        Nilai4 = new javax.swing.JTextField();
        Nilai5 = new javax.swing.JTextField();
        NilaiAkhir = new javax.swing.JTextField();
        Nilai1 = new javax.swing.JTextField();
        Simpan = new javax.swing.JButton();
        Hapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelMahasiswa = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(null);
        jPanel1.add(NIM);
        NIM.setBounds(130, 70, 130, 22);
        jPanel1.add(Nama);
        Nama.setBounds(130, 110, 130, 22);
        jPanel1.add(Alamat);
        Alamat.setBounds(130, 150, 130, 22);
        jPanel1.add(MataKuliah);
        MataKuliah.setBounds(130, 190, 130, 22);

        Nilai2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nilai2ActionPerformed(evt);
            }
        });
        jPanel1.add(Nilai2);
        Nilai2.setBounds(500, 110, 130, 22);
        jPanel1.add(Nilai3);
        Nilai3.setBounds(500, 150, 130, 22);
        jPanel1.add(Nilai4);
        Nilai4.setBounds(500, 190, 130, 22);
        jPanel1.add(Nilai5);
        Nilai5.setBounds(500, 230, 130, 22);
        jPanel1.add(NilaiAkhir);
        NilaiAkhir.setBounds(500, 270, 130, 22);

        Nilai1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nilai1ActionPerformed(evt);
            }
        });
        jPanel1.add(Nilai1);
        Nilai1.setBounds(500, 70, 130, 22);

        Simpan.setText("Simpan");
        Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanActionPerformed(evt);
            }
        });
        jPanel1.add(Simpan);
        Simpan.setBounds(110, 300, 72, 23);

        Hapus.setText("Hapus");
        Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusActionPerformed(evt);
            }
        });
        jPanel1.add(Hapus);
        Hapus.setBounds(210, 300, 72, 23);

        TabelMahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NIM", "Nama", "Alamat", "Mata Kuliah", "Nilai Akhir"
            }
        ));
        jScrollPane1.setViewportView(TabelMahasiswa);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 340, 670, 220);

        jLabel1.setText("NIM");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 66, 40, 30);

        jLabel2.setText("Nama");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 110, 60, 20);

        jLabel3.setText("Alamat");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 150, 60, 20);

        jLabel4.setText("Mata Kuliah");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 190, 90, 20);

        jLabel5.setText("Nilai 1 [10%]");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(350, 70, 80, 16);

        jLabel6.setText("Nilai 2 [15%]");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(350, 110, 80, 16);

        jLabel7.setText("Nilai 3 - UTS[25%]");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(350, 150, 95, 16);

        jLabel8.setText("Nilai 4 [15%]");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(350, 190, 66, 16);

        jLabel9.setText("Nilai 5 [35%]");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(350, 230, 66, 16);

        jLabel10.setText("Nilai Akhir");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(350, 270, 55, 16);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 729, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Nilai2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nilai2ActionPerformed
        // TODO add your handling code here: 
    }//GEN-LAST:event_Nilai2ActionPerformed

    private void SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanActionPerformed
        // TODO add your handling code here:
        double nilai1 = Double.parseDouble(Nilai1.getText());
        double nilai2 = Double.parseDouble(Nilai2.getText());
        double nilai3 = Double.parseDouble(Nilai3.getText());
        double nilai4 = Double.parseDouble(Nilai4.getText());   
        double nilai5 = Double.parseDouble(Nilai5.getText());
        double nilaiDouble = Double.parseDouble(Nilai1.getText());
        dataMahasiswa.simpanMahasiswa(NIM.getText(), Nama.getText(), Alamat.getText(), MataKuliah.getText(), nilai1, nilai2, nilai3, nilai4, nilai5);
        
        TabelMahasiswa();
        ClearTextField();
        JOptionPane.showMessageDialog(null, "Data berhasil disimpan!");
    }//GEN-LAST:event_SimpanActionPerformed

    private void Nilai1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nilai1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nilai1ActionPerformed

    private void HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusActionPerformed
        // TODO add your handling code here:
        dataMahasiswa.hapusMahasiswa(TabelMahasiswa.getSelectedRow()+1); 
        TabelMahasiswa();
    }//GEN-LAST:event_HapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NilaiMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NilaiMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NilaiMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NilaiMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NilaiMahasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Alamat;
    private javax.swing.JButton Hapus;
    private javax.swing.JTextField MataKuliah;
    private javax.swing.JTextField NIM;
    private javax.swing.JTextField Nama;
    private javax.swing.JTextField Nilai1;
    private javax.swing.JTextField Nilai2;
    private javax.swing.JTextField Nilai3;
    private javax.swing.JTextField Nilai4;
    private javax.swing.JTextField Nilai5;
    private javax.swing.JTextField NilaiAkhir;
    private javax.swing.JButton Simpan;
    private javax.swing.JTable TabelMahasiswa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
